name: Daily SP500 Tracker

on:
  schedule:
    - cron: '30 22 * * *' # Run daily at 22:30 UTC
  workflow_dispatch: # Allow manual run

jobs:
  fetch-sp500:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fetch and append SP500 data
        run: node get-sp500.js
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

      - name: Commit and push CSV if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sp500-data.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update SP500 data for $(date -u +'%Y-%m-%d')"
            git push
          fi